language: cpp
sudo: true
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsfml-dev
    - libglew-dev
    - gcc-5
    - g++-5

compiler:
    - g++

#Build steps
before_install:
    - wget https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz
    - tar xfv cmake-3.6.1-Linux-x86_64.tar.gz
    - rm -v cmake-3.6.1-Linux-x86_64.tar.gz
    - mv -v cmake-3.6.1-Linux-x86_64 cmake361
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    
script:
    - cmake361/bin/cmake .
    - make
