language: cpp
sudo: true
dist: trusty
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsfml-dev
    - libglew-dev

compiler:
    - g++

#Build steps
before_install:
    - wget https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz
    - tar xf cmake-3.6.1-Linux-x86_64.tar.gz
    - ln -s cmake-3.6.1-Linux-x86_64 cmake

script:
    - cmake/bin/cmake .
    - make
